name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
      REPOSITORY_USER: ${{ secrets.REPOSITORY_USER }}
      REPOSITORY_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: ./build.sh
    - name: Publish
      run: ./publish.sh
      